on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker version
      run: docker version
    - name: Docker build
      run: DOCKER_BUILDKIT=1 docker build .
